"""create table users

Revision ID: 8c4c7bc77c2f
Revises: 
Create Date: 2025-03-14 23:00:37.387780

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '8c4c7bc77c2f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
