"""Adicionando coluna title

Revision ID: 9451d6ef8600
Revises: 46f06b373287
Create Date: 2025-04-10 15:11:31.260540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9451d6ef8600'
down_revision: Union[str, None] = '46f06b373287'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('title', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'title')
    # ### end Alembic commands ###
